export const sampleExercises = [
  { label: "Barbell Bench Press", value: "barbell-bench-press" },
  { label: "DB Bench Press", value: "db-bench-press" },
  { label: "Incline Bench Press", value: "incline-bench-press" },
  { label: "Incline DB Bench Press", value: "incline-db-bench-press" },
  { label: "Decline Bench Press", value: "decline-bench-press" },
  { label: "High Cable Crossovers", value: "high-cable-crossovers" },
  { label: "Low Cable Crossovers", value: "low-cable-crossovers" },
  { label: "Push-Ups", value: "push-ups" },
  { label: "Pull-Ups", value: "pull-ups" },
  { label: "Chin-Ups", value: "chin-ups" },
  { label: "Lat Pulldowns", value: "lat-pulldowns" },
  { label: "Bent Over Rows", value: "bent-over-rows" },
  { label: "Seated Cable Rows", value: "seated-cable-rows" },
  { label: "1-Arm High Cable Rows", value: "1-arm-high-cable-rows" },
  { label: "T-Bar Rows", value: "t-bar-rows" },
  { label: "Meadows Rows", value: "meadows-rows" },
  { label: "Back Extensions", value: "back-extentsions" },
  { label: "Deadlifts", value: "deadlifts" },
  { label: "Romanian Deadlifts", value: "romanian-deadlifts" },
  { label: "Front Squats", value: "front-squats" },
  { label: "Back Squats", value: "back-squats" },
  { label: "Lunges", value: "lunges" },
  { label: "Bulgarian Split Squats", value: "bulgarian-split-squats" },
  { label: "Leg Press", value: "leg-press" },
  { label: "Calf Raises", value: "calf-raises" },
  { label: "Shoulder Press", value: "shoulder-press" },
  { label: "Arnold Press", value: "arnold-press" },
  { label: "Lateral Raises", value: "lateral-raises" },
  { label: "Front Raises", value: "front-raises" },
  { label: "Rear Delt Flys", value: "rear-delt-flys" },
  { label: "Face Pulls", value: "face-pulls" },
  { label: "External Rotations", value: "external-rotations" },
  { label: "Tricep Pushdowns", value: "tricep-pushdowns" },
  { label: "Skullcrushers", value: "skullcrushers" },
  { label: "Bicep Curls", value: "bicep-curls" },
  { label: "DB Bicep Curls", value: "db-bicep-curls" },
  { label: "Hammer Curls", value: "hammer-curls" },
  { label: "Barbell Curls", value: "barbell-curls" },
  { label: "Planks", value: "planks" },
  { label: "Crunches", value: "crunches" },
  { label: "Russian Twists", value: "russian-twists" },
  { label: "Leg Raises", value: "leg-raises" },
  { label: "Glute Bridges", value: "glute-bridges" },
  { label: "Hip Thrusts", value: "hip-thrusts" },
  { label: "Bicycle Kicks", value: "bicycle-kicks" },
  { label: "Gymnast Tucks", value: "gymnast-tucks" },
  { label: "Side Bridge Twists", value: "side-bridge-twists" },
  { label: "Ab Wheel Rollout", value: "ab-wheel-rollout" },
  { label: "Toe Touches", value: "toe-touches" },
];
