export const exercises = [
  { label: "Barbell Bench Press", value: "barbell-bench-press" },
  { label: "Dumbbell Bench Press", value: "dumbbell-bench-press" },
  { label: "Incline Bench Press", value: "incline-bench-press" },
  { label: "Decline Bench Press", value: "decline-bench-press" },
  { label: "Push-Ups", value: "push-ups" },
  { label: "Pull-Ups", value: "pull-ups" },
  { label: "Chin-Ups", value: "chin-ups" },
  { label: "Lat Pulldowns", value: "lat-pulldowns" },
  { label: "Bent Over Rows", value: "bent-over-rows" },
  { label: "Seated Cable Rows", value: "seated-cable-rows" },
  { label: "T-Bar Rows", value: "t-bar-rows" },
  { label: "Deadlifts", value: "deadlifts" },
  { label: "Squats", value: "squats" },
  { label: "Lunges", value: "lunges" },
  { label: "Bulgarian Split Squats", value: "bulgarian-split-squats" },
  { label: "Leg Press", value: "leg-press" },
  { label: "Calf Raises", value: "calf-raises" },
  { label: "Shoulder Press", value: "shoulder-press" },
  { label: "Arnold Press", value: "arnold-press" },
  { label: "Lateral Raises", value: "lateral-raises" },
  { label: "Front Raises", value: "front-raises" },
  { label: "Dumbbell Flys", value: "dumbbell-flys" },
  { label: "Tricep Pushdowns", value: "tricep-pushdowns" },
  { label: "Skullcrushers", value: "skullcrushers" },
  { label: "Bicep Curls", value: "bicep-curls" },
  { label: "Hammer Curls", value: "hammer-curls" },
  { label: "Barbell Curls", value: "barbell-curls" },
  { label: "Planks", value: "planks" },
  { label: "Crunches", value: "crunches" },
  { label: "Russian Twists", value: "russian-twists" },
  { label: "Leg Raises", value: "leg-raises" },
  { label: "Glute Bridges", value: "glute-bridges" },
  { label: "Hip Thrusts", value: "hip-thrusts" },
  { label: "Bicycle Kicks", value: "bicycle-kicks" }
];
